# Generated by Django 4.2.5 on 2023-09-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile.jpg', null=True, upload_to=''),
        ),
    ]
