# Generated by Django 4.2.5 on 2023-09-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
